/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
       colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          border: "hsl(var(--sidebar-border))",
        },
        header: {
          DEFAULT: "hsl(var(--header))",
          foreground: "hsl(var(--header-foreground))",
          border: "hsl(var(--header-border))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        error: {
          DEFAULT: "hsl(var(--error))",
          foreground: "hsl(var(--error-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        brand: {
          50: '#f4f6fe',
          100: '#ebedfe',
          200: '#dce0fe',
          300: '#c4cbfe',
          400: '#a3acf9',
          500: '#7e87f2',
          600: '#5c62e5',
          700: '#4a4ecc',
          800: '#3e41a6',
          900: '#343784',
          950: '#20214e',
        },
        // Mockup specific colors
        "surface-container-low": "#f4f3f6",
        "secondary-fixed-dim": "#aec6ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-container": "#a783ff",
        "primary-fixed": "#d2e4ff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e3e2e5",
        "surface-bright": "#faf9fc",
        "on-surface": "#1a1c1e",
        "surface-variant": "#e3e2e5",
        "on-secondary-fixed-variant": "#004397",
        "inverse-on-surface": "#f1f0f3",
        "on-primary": "#ffffff",
        "on-surface-variant": "#43474d",
        "on-primary-fixed-variant": "#2e4867",
        "secondary-container": "#6b9cff",
        "inverse-surface": "#2f3033",
        "surface": "#faf9fc",
        "on-primary-container": "#809abd",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#23005d",
        "on-primary-fixed": "#001d37",
        "on-secondary-fixed": "#001a43",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#23005c",
        "surface-dim": "#dad9dc",
        "on-tertiary-fixed-variant": "#5516be",
        "on-secondary-container": "#003275",
        "surface-container-high": "#e9e8ea",
        "tertiary-container": "#3c0092",
        "tertiary-fixed": "#e9ddff",
        "inverse-primary": "#aec9ed",
        "outline-variant": "#c3c6ce",
        "surface-container": "#efedf0",
        "primary-fixed-dim": "#aec9ed",
        "on-background": "#1a1c1e",
        "secondary": "#1e5bba",
        "tertiary-fixed-dim": "#d0bcff",
        "outline": "#74777e",
        "on-error-container": "#93000a",
        "surface-tint": "#466080",
        "primary-container": "#16324f"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        "page-title-mobile": ["Inter", "sans-serif"],
        "page-title": ["Inter", "sans-serif"],
        "data-tabular": ["IBM Plex Sans", "monospace"],
        "card-title": ["Inter", "sans-serif"],
        "section-title": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "page-title-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "page-title": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "450" }],
        "card-title": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "section-title": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }]
      },
      borderRadius: {
        'glass': '16px',
        'premium': '12px',
        'lg': '0.5rem',
        'md': 'calc(var(--radius) - 2px)',
        'sm': 'calc(var(--radius) - 4px)',
        'xl': '0.75rem',
        'full': '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        "section-gap": "24px",
        "unit": "4px",
        "card-padding": "20px",
        "grid-gutter": "16px",
        "container-padding": "32px"
      },
      boxShadow: {
        'glass-light': '0 8px 32px 0 rgba(31, 38, 135, 0.08)',
        'glass-dark': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
        'premium': '0 10px 30px -10px rgba(0, 0, 0, 0.1)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out forwards',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in': 'scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'pulse-subtle': 'pulseSubtle 2s infinite ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(16px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        }
      },
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
  },
  plugins: [],
}
